/**
 * @fileoverview gRPC-Web generated client stub for carapp
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.3
// source: carapp.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as carapp_pb from './carapp_pb'; // proto import: "carapp.proto"
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"


export class AuthServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRegister = new grpcWeb.MethodDescriptor(
    '/carapp.AuthService/Register',
    grpcWeb.MethodType.UNARY,
    carapp_pb.RegisterRequest,
    carapp_pb.AuthResponse,
    (request: carapp_pb.RegisterRequest) => {
      return request.serializeBinary();
    },
    carapp_pb.AuthResponse.deserializeBinary
  );

  register(
    request: carapp_pb.RegisterRequest,
    metadata?: grpcWeb.Metadata | null): Promise<carapp_pb.AuthResponse>;

  register(
    request: carapp_pb.RegisterRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: carapp_pb.AuthResponse) => void): grpcWeb.ClientReadableStream<carapp_pb.AuthResponse>;

  register(
    request: carapp_pb.RegisterRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: carapp_pb.AuthResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/carapp.AuthService/Register',
        request,
        metadata || {},
        this.methodDescriptorRegister,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/carapp.AuthService/Register',
    request,
    metadata || {},
    this.methodDescriptorRegister);
  }

  methodDescriptorLogin = new grpcWeb.MethodDescriptor(
    '/carapp.AuthService/Login',
    grpcWeb.MethodType.UNARY,
    carapp_pb.LoginRequest,
    carapp_pb.AuthResponse,
    (request: carapp_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    carapp_pb.AuthResponse.deserializeBinary
  );

  login(
    request: carapp_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null): Promise<carapp_pb.AuthResponse>;

  login(
    request: carapp_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: carapp_pb.AuthResponse) => void): grpcWeb.ClientReadableStream<carapp_pb.AuthResponse>;

  login(
    request: carapp_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: carapp_pb.AuthResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/carapp.AuthService/Login',
        request,
        metadata || {},
        this.methodDescriptorLogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/carapp.AuthService/Login',
    request,
    metadata || {},
    this.methodDescriptorLogin);
  }

}

export class MobilServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateMobil = new grpcWeb.MethodDescriptor(
    '/carapp.MobilService/CreateMobil',
    grpcWeb.MethodType.UNARY,
    carapp_pb.CreateMobilRequest,
    carapp_pb.Mobil,
    (request: carapp_pb.CreateMobilRequest) => {
      return request.serializeBinary();
    },
    carapp_pb.Mobil.deserializeBinary
  );

  createMobil(
    request: carapp_pb.CreateMobilRequest,
    metadata?: grpcWeb.Metadata | null): Promise<carapp_pb.Mobil>;

  createMobil(
    request: carapp_pb.CreateMobilRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: carapp_pb.Mobil) => void): grpcWeb.ClientReadableStream<carapp_pb.Mobil>;

  createMobil(
    request: carapp_pb.CreateMobilRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: carapp_pb.Mobil) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/carapp.MobilService/CreateMobil',
        request,
        metadata || {},
        this.methodDescriptorCreateMobil,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/carapp.MobilService/CreateMobil',
    request,
    metadata || {},
    this.methodDescriptorCreateMobil);
  }

  methodDescriptorListMobil = new grpcWeb.MethodDescriptor(
    '/carapp.MobilService/ListMobil',
    grpcWeb.MethodType.UNARY,
    carapp_pb.ListMobilRequest,
    carapp_pb.ListMobilResponse,
    (request: carapp_pb.ListMobilRequest) => {
      return request.serializeBinary();
    },
    carapp_pb.ListMobilResponse.deserializeBinary
  );

  listMobil(
    request: carapp_pb.ListMobilRequest,
    metadata?: grpcWeb.Metadata | null): Promise<carapp_pb.ListMobilResponse>;

  listMobil(
    request: carapp_pb.ListMobilRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: carapp_pb.ListMobilResponse) => void): grpcWeb.ClientReadableStream<carapp_pb.ListMobilResponse>;

  listMobil(
    request: carapp_pb.ListMobilRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: carapp_pb.ListMobilResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/carapp.MobilService/ListMobil',
        request,
        metadata || {},
        this.methodDescriptorListMobil,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/carapp.MobilService/ListMobil',
    request,
    metadata || {},
    this.methodDescriptorListMobil);
  }

  methodDescriptorGetMobil = new grpcWeb.MethodDescriptor(
    '/carapp.MobilService/GetMobil',
    grpcWeb.MethodType.UNARY,
    carapp_pb.GetMobilRequest,
    carapp_pb.Mobil,
    (request: carapp_pb.GetMobilRequest) => {
      return request.serializeBinary();
    },
    carapp_pb.Mobil.deserializeBinary
  );

  getMobil(
    request: carapp_pb.GetMobilRequest,
    metadata?: grpcWeb.Metadata | null): Promise<carapp_pb.Mobil>;

  getMobil(
    request: carapp_pb.GetMobilRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: carapp_pb.Mobil) => void): grpcWeb.ClientReadableStream<carapp_pb.Mobil>;

  getMobil(
    request: carapp_pb.GetMobilRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: carapp_pb.Mobil) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/carapp.MobilService/GetMobil',
        request,
        metadata || {},
        this.methodDescriptorGetMobil,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/carapp.MobilService/GetMobil',
    request,
    metadata || {},
    this.methodDescriptorGetMobil);
  }

}

export class NhtsaDataServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetMakes = new grpcWeb.MethodDescriptor(
    '/carapp.NhtsaDataService/GetMakes',
    grpcWeb.MethodType.UNARY,
    carapp_pb.GetMakesRequest,
    carapp_pb.GetMakesResponse,
    (request: carapp_pb.GetMakesRequest) => {
      return request.serializeBinary();
    },
    carapp_pb.GetMakesResponse.deserializeBinary
  );

  getMakes(
    request: carapp_pb.GetMakesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<carapp_pb.GetMakesResponse>;

  getMakes(
    request: carapp_pb.GetMakesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: carapp_pb.GetMakesResponse) => void): grpcWeb.ClientReadableStream<carapp_pb.GetMakesResponse>;

  getMakes(
    request: carapp_pb.GetMakesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: carapp_pb.GetMakesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/carapp.NhtsaDataService/GetMakes',
        request,
        metadata || {},
        this.methodDescriptorGetMakes,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/carapp.NhtsaDataService/GetMakes',
    request,
    metadata || {},
    this.methodDescriptorGetMakes);
  }

  methodDescriptorGetModelsForMake = new grpcWeb.MethodDescriptor(
    '/carapp.NhtsaDataService/GetModelsForMake',
    grpcWeb.MethodType.UNARY,
    carapp_pb.GetModelsForMakeRequest,
    carapp_pb.GetModelsForMakeResponse,
    (request: carapp_pb.GetModelsForMakeRequest) => {
      return request.serializeBinary();
    },
    carapp_pb.GetModelsForMakeResponse.deserializeBinary
  );

  getModelsForMake(
    request: carapp_pb.GetModelsForMakeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<carapp_pb.GetModelsForMakeResponse>;

  getModelsForMake(
    request: carapp_pb.GetModelsForMakeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: carapp_pb.GetModelsForMakeResponse) => void): grpcWeb.ClientReadableStream<carapp_pb.GetModelsForMakeResponse>;

  getModelsForMake(
    request: carapp_pb.GetModelsForMakeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: carapp_pb.GetModelsForMakeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/carapp.NhtsaDataService/GetModelsForMake',
        request,
        metadata || {},
        this.methodDescriptorGetModelsForMake,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/carapp.NhtsaDataService/GetModelsForMake',
    request,
    metadata || {},
    this.methodDescriptorGetModelsForMake);
  }

}

export class TransaksiServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorBuyMobil = new grpcWeb.MethodDescriptor(
    '/carapp.TransaksiService/BuyMobil',
    grpcWeb.MethodType.UNARY,
    carapp_pb.BuyMobilRequest,
    carapp_pb.TransaksiJualResponse,
    (request: carapp_pb.BuyMobilRequest) => {
      return request.serializeBinary();
    },
    carapp_pb.TransaksiJualResponse.deserializeBinary
  );

  buyMobil(
    request: carapp_pb.BuyMobilRequest,
    metadata?: grpcWeb.Metadata | null): Promise<carapp_pb.TransaksiJualResponse>;

  buyMobil(
    request: carapp_pb.BuyMobilRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: carapp_pb.TransaksiJualResponse) => void): grpcWeb.ClientReadableStream<carapp_pb.TransaksiJualResponse>;

  buyMobil(
    request: carapp_pb.BuyMobilRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: carapp_pb.TransaksiJualResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/carapp.TransaksiService/BuyMobil',
        request,
        metadata || {},
        this.methodDescriptorBuyMobil,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/carapp.TransaksiService/BuyMobil',
    request,
    metadata || {},
    this.methodDescriptorBuyMobil);
  }

  methodDescriptorRentMobil = new grpcWeb.MethodDescriptor(
    '/carapp.TransaksiService/RentMobil',
    grpcWeb.MethodType.UNARY,
    carapp_pb.RentMobilRequest,
    carapp_pb.TransaksiRentalResponse,
    (request: carapp_pb.RentMobilRequest) => {
      return request.serializeBinary();
    },
    carapp_pb.TransaksiRentalResponse.deserializeBinary
  );

  rentMobil(
    request: carapp_pb.RentMobilRequest,
    metadata?: grpcWeb.Metadata | null): Promise<carapp_pb.TransaksiRentalResponse>;

  rentMobil(
    request: carapp_pb.RentMobilRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: carapp_pb.TransaksiRentalResponse) => void): grpcWeb.ClientReadableStream<carapp_pb.TransaksiRentalResponse>;

  rentMobil(
    request: carapp_pb.RentMobilRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: carapp_pb.TransaksiRentalResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/carapp.TransaksiService/RentMobil',
        request,
        metadata || {},
        this.methodDescriptorRentMobil,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/carapp.TransaksiService/RentMobil',
    request,
    metadata || {},
    this.methodDescriptorRentMobil);
  }

  methodDescriptorCompleteRental = new grpcWeb.MethodDescriptor(
    '/carapp.TransaksiService/CompleteRental',
    grpcWeb.MethodType.UNARY,
    carapp_pb.CompleteRentalRequest,
    carapp_pb.TransaksiRentalResponse,
    (request: carapp_pb.CompleteRentalRequest) => {
      return request.serializeBinary();
    },
    carapp_pb.TransaksiRentalResponse.deserializeBinary
  );

  completeRental(
    request: carapp_pb.CompleteRentalRequest,
    metadata?: grpcWeb.Metadata | null): Promise<carapp_pb.TransaksiRentalResponse>;

  completeRental(
    request: carapp_pb.CompleteRentalRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: carapp_pb.TransaksiRentalResponse) => void): grpcWeb.ClientReadableStream<carapp_pb.TransaksiRentalResponse>;

  completeRental(
    request: carapp_pb.CompleteRentalRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: carapp_pb.TransaksiRentalResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/carapp.TransaksiService/CompleteRental',
        request,
        metadata || {},
        this.methodDescriptorCompleteRental,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/carapp.TransaksiService/CompleteRental',
    request,
    metadata || {},
    this.methodDescriptorCompleteRental);
  }

}

export class NotifikasiServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetNotifications = new grpcWeb.MethodDescriptor(
    '/carapp.NotifikasiService/GetNotifications',
    grpcWeb.MethodType.SERVER_STREAMING,
    carapp_pb.GetNotificationsRequest,
    carapp_pb.Notifikasi,
    (request: carapp_pb.GetNotificationsRequest) => {
      return request.serializeBinary();
    },
    carapp_pb.Notifikasi.deserializeBinary
  );

  getNotifications(
    request: carapp_pb.GetNotificationsRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<carapp_pb.Notifikasi> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/carapp.NotifikasiService/GetNotifications',
      request,
      metadata || {},
      this.methodDescriptorGetNotifications);
  }

}

export class DashboardServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetDashboard = new grpcWeb.MethodDescriptor(
    '/carapp.DashboardService/GetDashboard',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    carapp_pb.DashboardSummary,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    carapp_pb.DashboardSummary.deserializeBinary
  );

  getDashboard(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<carapp_pb.DashboardSummary>;

  getDashboard(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: carapp_pb.DashboardSummary) => void): grpcWeb.ClientReadableStream<carapp_pb.DashboardSummary>;

  getDashboard(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: carapp_pb.DashboardSummary) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/carapp.DashboardService/GetDashboard',
        request,
        metadata || {},
        this.methodDescriptorGetDashboard,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/carapp.DashboardService/GetDashboard',
    request,
    metadata || {},
    this.methodDescriptorGetDashboard);
  }

}

