// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/carapp.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_Register_FullMethodName = "/carapp.AuthService/Register"
	AuthService_Login_FullMethodName    = "/carapp.AuthService/Login"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	Register(context.Context, *RegisterRequest) (*AuthResponse, error)
	Login(context.Context, *LoginRequest) (*AuthResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) Register(context.Context, *RegisterRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "carapp.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AuthService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/carapp.proto",
}

const (
	MobilService_CreateMobil_FullMethodName = "/carapp.MobilService/CreateMobil"
	MobilService_ListMobil_FullMethodName   = "/carapp.MobilService/ListMobil"
	MobilService_GetMobil_FullMethodName    = "/carapp.MobilService/GetMobil"
)

// MobilServiceClient is the client API for MobilService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MobilServiceClient interface {
	// Fitur 4: Jual Mobil
	CreateMobil(ctx context.Context, in *CreateMobilRequest, opts ...grpc.CallOption) (*Mobil, error)
	// Fitur 2: List Mobil (dari DB kita)
	ListMobil(ctx context.Context, in *ListMobilRequest, opts ...grpc.CallOption) (*ListMobilResponse, error)
	// Fitur 3: Detail Mobil
	GetMobil(ctx context.Context, in *GetMobilRequest, opts ...grpc.CallOption) (*Mobil, error)
}

type mobilServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMobilServiceClient(cc grpc.ClientConnInterface) MobilServiceClient {
	return &mobilServiceClient{cc}
}

func (c *mobilServiceClient) CreateMobil(ctx context.Context, in *CreateMobilRequest, opts ...grpc.CallOption) (*Mobil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mobil)
	err := c.cc.Invoke(ctx, MobilService_CreateMobil_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobilServiceClient) ListMobil(ctx context.Context, in *ListMobilRequest, opts ...grpc.CallOption) (*ListMobilResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMobilResponse)
	err := c.cc.Invoke(ctx, MobilService_ListMobil_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobilServiceClient) GetMobil(ctx context.Context, in *GetMobilRequest, opts ...grpc.CallOption) (*Mobil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mobil)
	err := c.cc.Invoke(ctx, MobilService_GetMobil_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MobilServiceServer is the server API for MobilService service.
// All implementations must embed UnimplementedMobilServiceServer
// for forward compatibility.
type MobilServiceServer interface {
	// Fitur 4: Jual Mobil
	CreateMobil(context.Context, *CreateMobilRequest) (*Mobil, error)
	// Fitur 2: List Mobil (dari DB kita)
	ListMobil(context.Context, *ListMobilRequest) (*ListMobilResponse, error)
	// Fitur 3: Detail Mobil
	GetMobil(context.Context, *GetMobilRequest) (*Mobil, error)
	mustEmbedUnimplementedMobilServiceServer()
}

// UnimplementedMobilServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMobilServiceServer struct{}

func (UnimplementedMobilServiceServer) CreateMobil(context.Context, *CreateMobilRequest) (*Mobil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMobil not implemented")
}
func (UnimplementedMobilServiceServer) ListMobil(context.Context, *ListMobilRequest) (*ListMobilResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMobil not implemented")
}
func (UnimplementedMobilServiceServer) GetMobil(context.Context, *GetMobilRequest) (*Mobil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMobil not implemented")
}
func (UnimplementedMobilServiceServer) mustEmbedUnimplementedMobilServiceServer() {}
func (UnimplementedMobilServiceServer) testEmbeddedByValue()                      {}

// UnsafeMobilServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MobilServiceServer will
// result in compilation errors.
type UnsafeMobilServiceServer interface {
	mustEmbedUnimplementedMobilServiceServer()
}

func RegisterMobilServiceServer(s grpc.ServiceRegistrar, srv MobilServiceServer) {
	// If the following call pancis, it indicates UnimplementedMobilServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MobilService_ServiceDesc, srv)
}

func _MobilService_CreateMobil_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMobilRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobilServiceServer).CreateMobil(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MobilService_CreateMobil_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobilServiceServer).CreateMobil(ctx, req.(*CreateMobilRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MobilService_ListMobil_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMobilRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobilServiceServer).ListMobil(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MobilService_ListMobil_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobilServiceServer).ListMobil(ctx, req.(*ListMobilRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MobilService_GetMobil_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMobilRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobilServiceServer).GetMobil(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MobilService_GetMobil_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobilServiceServer).GetMobil(ctx, req.(*GetMobilRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MobilService_ServiceDesc is the grpc.ServiceDesc for MobilService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MobilService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "carapp.MobilService",
	HandlerType: (*MobilServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMobil",
			Handler:    _MobilService_CreateMobil_Handler,
		},
		{
			MethodName: "ListMobil",
			Handler:    _MobilService_ListMobil_Handler,
		},
		{
			MethodName: "GetMobil",
			Handler:    _MobilService_GetMobil_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/carapp.proto",
}

const (
	NhtsaDataService_GetMakes_FullMethodName         = "/carapp.NhtsaDataService/GetMakes"
	NhtsaDataService_GetModelsForMake_FullMethodName = "/carapp.NhtsaDataService/GetModelsForMake"
)

// NhtsaDataServiceClient is the client API for NhtsaDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NhtsaDataServiceClient interface {
	// Prasyarat Fitur 4: Mendapat data dari NHTSA API (Cache)
	GetMakes(ctx context.Context, in *GetMakesRequest, opts ...grpc.CallOption) (*GetMakesResponse, error)
	GetModelsForMake(ctx context.Context, in *GetModelsForMakeRequest, opts ...grpc.CallOption) (*GetModelsForMakeResponse, error)
}

type nhtsaDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNhtsaDataServiceClient(cc grpc.ClientConnInterface) NhtsaDataServiceClient {
	return &nhtsaDataServiceClient{cc}
}

func (c *nhtsaDataServiceClient) GetMakes(ctx context.Context, in *GetMakesRequest, opts ...grpc.CallOption) (*GetMakesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMakesResponse)
	err := c.cc.Invoke(ctx, NhtsaDataService_GetMakes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nhtsaDataServiceClient) GetModelsForMake(ctx context.Context, in *GetModelsForMakeRequest, opts ...grpc.CallOption) (*GetModelsForMakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelsForMakeResponse)
	err := c.cc.Invoke(ctx, NhtsaDataService_GetModelsForMake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NhtsaDataServiceServer is the server API for NhtsaDataService service.
// All implementations must embed UnimplementedNhtsaDataServiceServer
// for forward compatibility.
type NhtsaDataServiceServer interface {
	// Prasyarat Fitur 4: Mendapat data dari NHTSA API (Cache)
	GetMakes(context.Context, *GetMakesRequest) (*GetMakesResponse, error)
	GetModelsForMake(context.Context, *GetModelsForMakeRequest) (*GetModelsForMakeResponse, error)
	mustEmbedUnimplementedNhtsaDataServiceServer()
}

// UnimplementedNhtsaDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNhtsaDataServiceServer struct{}

func (UnimplementedNhtsaDataServiceServer) GetMakes(context.Context, *GetMakesRequest) (*GetMakesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMakes not implemented")
}
func (UnimplementedNhtsaDataServiceServer) GetModelsForMake(context.Context, *GetModelsForMakeRequest) (*GetModelsForMakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelsForMake not implemented")
}
func (UnimplementedNhtsaDataServiceServer) mustEmbedUnimplementedNhtsaDataServiceServer() {}
func (UnimplementedNhtsaDataServiceServer) testEmbeddedByValue()                          {}

// UnsafeNhtsaDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NhtsaDataServiceServer will
// result in compilation errors.
type UnsafeNhtsaDataServiceServer interface {
	mustEmbedUnimplementedNhtsaDataServiceServer()
}

func RegisterNhtsaDataServiceServer(s grpc.ServiceRegistrar, srv NhtsaDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedNhtsaDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NhtsaDataService_ServiceDesc, srv)
}

func _NhtsaDataService_GetMakes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMakesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NhtsaDataServiceServer).GetMakes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NhtsaDataService_GetMakes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NhtsaDataServiceServer).GetMakes(ctx, req.(*GetMakesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NhtsaDataService_GetModelsForMake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelsForMakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NhtsaDataServiceServer).GetModelsForMake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NhtsaDataService_GetModelsForMake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NhtsaDataServiceServer).GetModelsForMake(ctx, req.(*GetModelsForMakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NhtsaDataService_ServiceDesc is the grpc.ServiceDesc for NhtsaDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NhtsaDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "carapp.NhtsaDataService",
	HandlerType: (*NhtsaDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMakes",
			Handler:    _NhtsaDataService_GetMakes_Handler,
		},
		{
			MethodName: "GetModelsForMake",
			Handler:    _NhtsaDataService_GetModelsForMake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/carapp.proto",
}

const (
	TransaksiService_BuyMobil_FullMethodName       = "/carapp.TransaksiService/BuyMobil"
	TransaksiService_RentMobil_FullMethodName      = "/carapp.TransaksiService/RentMobil"
	TransaksiService_CompleteRental_FullMethodName = "/carapp.TransaksiService/CompleteRental"
)

// TransaksiServiceClient is the client API for TransaksiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransaksiServiceClient interface {
	// Fitur 3: Beli Mobil
	BuyMobil(ctx context.Context, in *BuyMobilRequest, opts ...grpc.CallOption) (*TransaksiJualResponse, error)
	// Fitur 3 & 5: Rental Mobil
	RentMobil(ctx context.Context, in *RentMobilRequest, opts ...grpc.CallOption) (*TransaksiRentalResponse, error)
	CompleteRental(ctx context.Context, in *CompleteRentalRequest, opts ...grpc.CallOption) (*TransaksiRentalResponse, error)
}

type transaksiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransaksiServiceClient(cc grpc.ClientConnInterface) TransaksiServiceClient {
	return &transaksiServiceClient{cc}
}

func (c *transaksiServiceClient) BuyMobil(ctx context.Context, in *BuyMobilRequest, opts ...grpc.CallOption) (*TransaksiJualResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransaksiJualResponse)
	err := c.cc.Invoke(ctx, TransaksiService_BuyMobil_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transaksiServiceClient) RentMobil(ctx context.Context, in *RentMobilRequest, opts ...grpc.CallOption) (*TransaksiRentalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransaksiRentalResponse)
	err := c.cc.Invoke(ctx, TransaksiService_RentMobil_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transaksiServiceClient) CompleteRental(ctx context.Context, in *CompleteRentalRequest, opts ...grpc.CallOption) (*TransaksiRentalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransaksiRentalResponse)
	err := c.cc.Invoke(ctx, TransaksiService_CompleteRental_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransaksiServiceServer is the server API for TransaksiService service.
// All implementations must embed UnimplementedTransaksiServiceServer
// for forward compatibility.
type TransaksiServiceServer interface {
	// Fitur 3: Beli Mobil
	BuyMobil(context.Context, *BuyMobilRequest) (*TransaksiJualResponse, error)
	// Fitur 3 & 5: Rental Mobil
	RentMobil(context.Context, *RentMobilRequest) (*TransaksiRentalResponse, error)
	CompleteRental(context.Context, *CompleteRentalRequest) (*TransaksiRentalResponse, error)
	mustEmbedUnimplementedTransaksiServiceServer()
}

// UnimplementedTransaksiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransaksiServiceServer struct{}

func (UnimplementedTransaksiServiceServer) BuyMobil(context.Context, *BuyMobilRequest) (*TransaksiJualResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyMobil not implemented")
}
func (UnimplementedTransaksiServiceServer) RentMobil(context.Context, *RentMobilRequest) (*TransaksiRentalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RentMobil not implemented")
}
func (UnimplementedTransaksiServiceServer) CompleteRental(context.Context, *CompleteRentalRequest) (*TransaksiRentalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteRental not implemented")
}
func (UnimplementedTransaksiServiceServer) mustEmbedUnimplementedTransaksiServiceServer() {}
func (UnimplementedTransaksiServiceServer) testEmbeddedByValue()                          {}

// UnsafeTransaksiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransaksiServiceServer will
// result in compilation errors.
type UnsafeTransaksiServiceServer interface {
	mustEmbedUnimplementedTransaksiServiceServer()
}

func RegisterTransaksiServiceServer(s grpc.ServiceRegistrar, srv TransaksiServiceServer) {
	// If the following call pancis, it indicates UnimplementedTransaksiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransaksiService_ServiceDesc, srv)
}

func _TransaksiService_BuyMobil_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyMobilRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransaksiServiceServer).BuyMobil(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransaksiService_BuyMobil_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransaksiServiceServer).BuyMobil(ctx, req.(*BuyMobilRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransaksiService_RentMobil_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RentMobilRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransaksiServiceServer).RentMobil(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransaksiService_RentMobil_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransaksiServiceServer).RentMobil(ctx, req.(*RentMobilRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransaksiService_CompleteRental_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRentalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransaksiServiceServer).CompleteRental(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransaksiService_CompleteRental_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransaksiServiceServer).CompleteRental(ctx, req.(*CompleteRentalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransaksiService_ServiceDesc is the grpc.ServiceDesc for TransaksiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransaksiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "carapp.TransaksiService",
	HandlerType: (*TransaksiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuyMobil",
			Handler:    _TransaksiService_BuyMobil_Handler,
		},
		{
			MethodName: "RentMobil",
			Handler:    _TransaksiService_RentMobil_Handler,
		},
		{
			MethodName: "CompleteRental",
			Handler:    _TransaksiService_CompleteRental_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/carapp.proto",
}

const (
	NotifikasiService_GetNotifications_FullMethodName = "/carapp.NotifikasiService/GetNotifications"
)

// NotifikasiServiceClient is the client API for NotifikasiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotifikasiServiceClient interface {
	// Fitur 6: Notifikasi
	GetNotifications(ctx context.Context, in *GetNotificationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notifikasi], error)
}

type notifikasiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifikasiServiceClient(cc grpc.ClientConnInterface) NotifikasiServiceClient {
	return &notifikasiServiceClient{cc}
}

func (c *notifikasiServiceClient) GetNotifications(ctx context.Context, in *GetNotificationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notifikasi], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NotifikasiService_ServiceDesc.Streams[0], NotifikasiService_GetNotifications_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetNotificationsRequest, Notifikasi]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NotifikasiService_GetNotificationsClient = grpc.ServerStreamingClient[Notifikasi]

// NotifikasiServiceServer is the server API for NotifikasiService service.
// All implementations must embed UnimplementedNotifikasiServiceServer
// for forward compatibility.
type NotifikasiServiceServer interface {
	// Fitur 6: Notifikasi
	GetNotifications(*GetNotificationsRequest, grpc.ServerStreamingServer[Notifikasi]) error
	mustEmbedUnimplementedNotifikasiServiceServer()
}

// UnimplementedNotifikasiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotifikasiServiceServer struct{}

func (UnimplementedNotifikasiServiceServer) GetNotifications(*GetNotificationsRequest, grpc.ServerStreamingServer[Notifikasi]) error {
	return status.Errorf(codes.Unimplemented, "method GetNotifications not implemented")
}
func (UnimplementedNotifikasiServiceServer) mustEmbedUnimplementedNotifikasiServiceServer() {}
func (UnimplementedNotifikasiServiceServer) testEmbeddedByValue()                           {}

// UnsafeNotifikasiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifikasiServiceServer will
// result in compilation errors.
type UnsafeNotifikasiServiceServer interface {
	mustEmbedUnimplementedNotifikasiServiceServer()
}

func RegisterNotifikasiServiceServer(s grpc.ServiceRegistrar, srv NotifikasiServiceServer) {
	// If the following call pancis, it indicates UnimplementedNotifikasiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotifikasiService_ServiceDesc, srv)
}

func _NotifikasiService_GetNotifications_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetNotificationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NotifikasiServiceServer).GetNotifications(m, &grpc.GenericServerStream[GetNotificationsRequest, Notifikasi]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NotifikasiService_GetNotificationsServer = grpc.ServerStreamingServer[Notifikasi]

// NotifikasiService_ServiceDesc is the grpc.ServiceDesc for NotifikasiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotifikasiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "carapp.NotifikasiService",
	HandlerType: (*NotifikasiServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetNotifications",
			Handler:       _NotifikasiService_GetNotifications_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/carapp.proto",
}

const (
	DashboardService_GetDashboard_FullMethodName = "/carapp.DashboardService/GetDashboard"
)

// DashboardServiceClient is the client API for DashboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DashboardServiceClient interface {
	// Fitur Rencana: Dashboard
	GetDashboard(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DashboardSummary, error)
}

type dashboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDashboardServiceClient(cc grpc.ClientConnInterface) DashboardServiceClient {
	return &dashboardServiceClient{cc}
}

func (c *dashboardServiceClient) GetDashboard(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DashboardSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardSummary)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DashboardServiceServer is the server API for DashboardService service.
// All implementations must embed UnimplementedDashboardServiceServer
// for forward compatibility.
type DashboardServiceServer interface {
	// Fitur Rencana: Dashboard
	GetDashboard(context.Context, *emptypb.Empty) (*DashboardSummary, error)
	mustEmbedUnimplementedDashboardServiceServer()
}

// UnimplementedDashboardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDashboardServiceServer struct{}

func (UnimplementedDashboardServiceServer) GetDashboard(context.Context, *emptypb.Empty) (*DashboardSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboard not implemented")
}
func (UnimplementedDashboardServiceServer) mustEmbedUnimplementedDashboardServiceServer() {}
func (UnimplementedDashboardServiceServer) testEmbeddedByValue()                          {}

// UnsafeDashboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DashboardServiceServer will
// result in compilation errors.
type UnsafeDashboardServiceServer interface {
	mustEmbedUnimplementedDashboardServiceServer()
}

func RegisterDashboardServiceServer(s grpc.ServiceRegistrar, srv DashboardServiceServer) {
	// If the following call pancis, it indicates UnimplementedDashboardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DashboardService_ServiceDesc, srv)
}

func _DashboardService_GetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboard(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DashboardService_ServiceDesc is the grpc.ServiceDesc for DashboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DashboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "carapp.DashboardService",
	HandlerType: (*DashboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDashboard",
			Handler:    _DashboardService_GetDashboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/carapp.proto",
}
