// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: proto/carapp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_carapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Mobil struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId            string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerName          string                 `protobuf:"bytes,13,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	Merk               string                 `protobuf:"bytes,3,opt,name=merk,proto3" json:"merk,omitempty"`
	Model              string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Tahun              int32                  `protobuf:"varint,5,opt,name=tahun,proto3" json:"tahun,omitempty"`
	Kondisi            string                 `protobuf:"bytes,6,opt,name=kondisi,proto3" json:"kondisi,omitempty"`
	Deskripsi          string                 `protobuf:"bytes,7,opt,name=deskripsi,proto3" json:"deskripsi,omitempty"`
	HargaJual          float64                `protobuf:"fixed64,8,opt,name=harga_jual,json=hargaJual,proto3" json:"harga_jual,omitempty"`
	FotoUrl            string                 `protobuf:"bytes,9,opt,name=foto_url,json=fotoUrl,proto3" json:"foto_url,omitempty"`
	Lokasi             string                 `protobuf:"bytes,10,opt,name=lokasi,proto3" json:"lokasi,omitempty"`
	Status             string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	HargaRentalPerHari float64                `protobuf:"fixed64,14,opt,name=harga_rental_per_hari,json=hargaRentalPerHari,proto3" json:"harga_rental_per_hari,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Mobil) Reset() {
	*x = Mobil{}
	mi := &file_proto_carapp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mobil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mobil) ProtoMessage() {}

func (x *Mobil) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mobil.ProtoReflect.Descriptor instead.
func (*Mobil) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{1}
}

func (x *Mobil) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Mobil) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Mobil) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Mobil) GetMerk() string {
	if x != nil {
		return x.Merk
	}
	return ""
}

func (x *Mobil) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Mobil) GetTahun() int32 {
	if x != nil {
		return x.Tahun
	}
	return 0
}

func (x *Mobil) GetKondisi() string {
	if x != nil {
		return x.Kondisi
	}
	return ""
}

func (x *Mobil) GetDeskripsi() string {
	if x != nil {
		return x.Deskripsi
	}
	return ""
}

func (x *Mobil) GetHargaJual() float64 {
	if x != nil {
		return x.HargaJual
	}
	return 0
}

func (x *Mobil) GetFotoUrl() string {
	if x != nil {
		return x.FotoUrl
	}
	return ""
}

func (x *Mobil) GetLokasi() string {
	if x != nil {
		return x.Lokasi
	}
	return ""
}

func (x *Mobil) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Mobil) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Mobil) GetHargaRentalPerHari() float64 {
	if x != nil {
		return x.HargaRentalPerHari
	}
	return 0
}

type Notifikasi struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tipe          string                 `protobuf:"bytes,3,opt,name=tipe,proto3" json:"tipe,omitempty"`
	Pesan         string                 `protobuf:"bytes,4,opt,name=pesan,proto3" json:"pesan,omitempty"`
	Priority      string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	ReadAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notifikasi) Reset() {
	*x = Notifikasi{}
	mi := &file_proto_carapp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notifikasi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notifikasi) ProtoMessage() {}

func (x *Notifikasi) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notifikasi.ProtoReflect.Descriptor instead.
func (*Notifikasi) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{2}
}

func (x *Notifikasi) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notifikasi) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notifikasi) GetTipe() string {
	if x != nil {
		return x.Tipe
	}
	return ""
}

func (x *Notifikasi) GetPesan() string {
	if x != nil {
		return x.Pesan
	}
	return ""
}

func (x *Notifikasi) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Notifikasi) GetReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadAt
	}
	return nil
}

func (x *Notifikasi) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_carapp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_carapp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_carapp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{5}
}

func (x *AuthResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateMobilRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// owner_id diambil dari JWT Token
	Merk               string  `protobuf:"bytes,1,opt,name=merk,proto3" json:"merk,omitempty"`
	Model              string  `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Tahun              int32   `protobuf:"varint,3,opt,name=tahun,proto3" json:"tahun,omitempty"`
	Kondisi            string  `protobuf:"bytes,4,opt,name=kondisi,proto3" json:"kondisi,omitempty"`
	Deskripsi          string  `protobuf:"bytes,5,opt,name=deskripsi,proto3" json:"deskripsi,omitempty"`
	HargaJual          float64 `protobuf:"fixed64,6,opt,name=harga_jual,json=hargaJual,proto3" json:"harga_jual,omitempty"`
	FotoUrl            string  `protobuf:"bytes,7,opt,name=foto_url,json=fotoUrl,proto3" json:"foto_url,omitempty"`
	Lokasi             string  `protobuf:"bytes,8,opt,name=lokasi,proto3" json:"lokasi,omitempty"`
	HargaRentalPerHari float64 `protobuf:"fixed64,9,opt,name=harga_rental_per_hari,json=hargaRentalPerHari,proto3" json:"harga_rental_per_hari,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateMobilRequest) Reset() {
	*x = CreateMobilRequest{}
	mi := &file_proto_carapp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMobilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMobilRequest) ProtoMessage() {}

func (x *CreateMobilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMobilRequest.ProtoReflect.Descriptor instead.
func (*CreateMobilRequest) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMobilRequest) GetMerk() string {
	if x != nil {
		return x.Merk
	}
	return ""
}

func (x *CreateMobilRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateMobilRequest) GetTahun() int32 {
	if x != nil {
		return x.Tahun
	}
	return 0
}

func (x *CreateMobilRequest) GetKondisi() string {
	if x != nil {
		return x.Kondisi
	}
	return ""
}

func (x *CreateMobilRequest) GetDeskripsi() string {
	if x != nil {
		return x.Deskripsi
	}
	return ""
}

func (x *CreateMobilRequest) GetHargaJual() float64 {
	if x != nil {
		return x.HargaJual
	}
	return 0
}

func (x *CreateMobilRequest) GetFotoUrl() string {
	if x != nil {
		return x.FotoUrl
	}
	return ""
}

func (x *CreateMobilRequest) GetLokasi() string {
	if x != nil {
		return x.Lokasi
	}
	return ""
}

func (x *CreateMobilRequest) GetHargaRentalPerHari() float64 {
	if x != nil {
		return x.HargaRentalPerHari
	}
	return 0
}

type ListMobilRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	FilterStatus  *string                `protobuf:"bytes,3,opt,name=filter_status,json=filterStatus,proto3,oneof" json:"filter_status,omitempty"` // "tersedia", "terjual", dll.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMobilRequest) Reset() {
	*x = ListMobilRequest{}
	mi := &file_proto_carapp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMobilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMobilRequest) ProtoMessage() {}

func (x *ListMobilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMobilRequest.ProtoReflect.Descriptor instead.
func (*ListMobilRequest) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{7}
}

func (x *ListMobilRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMobilRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMobilRequest) GetFilterStatus() string {
	if x != nil && x.FilterStatus != nil {
		return *x.FilterStatus
	}
	return ""
}

type ListMobilResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobils        []*Mobil               `protobuf:"bytes,1,rep,name=mobils,proto3" json:"mobils,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMobilResponse) Reset() {
	*x = ListMobilResponse{}
	mi := &file_proto_carapp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMobilResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMobilResponse) ProtoMessage() {}

func (x *ListMobilResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMobilResponse.ProtoReflect.Descriptor instead.
func (*ListMobilResponse) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{8}
}

func (x *ListMobilResponse) GetMobils() []*Mobil {
	if x != nil {
		return x.Mobils
	}
	return nil
}

func (x *ListMobilResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetMobilRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MobilId       string                 `protobuf:"bytes,1,opt,name=mobil_id,json=mobilId,proto3" json:"mobil_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMobilRequest) Reset() {
	*x = GetMobilRequest{}
	mi := &file_proto_carapp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMobilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMobilRequest) ProtoMessage() {}

func (x *GetMobilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMobilRequest.ProtoReflect.Descriptor instead.
func (*GetMobilRequest) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{9}
}

func (x *GetMobilRequest) GetMobilId() string {
	if x != nil {
		return x.MobilId
	}
	return ""
}

// Pesan untuk NHTSA Cache
type Make struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrandId       string                 `protobuf:"bytes,1,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Make) Reset() {
	*x = Make{}
	mi := &file_proto_carapp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Make) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Make) ProtoMessage() {}

func (x *Make) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Make.ProtoReflect.Descriptor instead.
func (*Make) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{10}
}

func (x *Make) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

func (x *Make) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	BrandId       string                 `protobuf:"bytes,2,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_proto_carapp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{11}
}

func (x *Model) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *Model) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetMakesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMakesRequest) Reset() {
	*x = GetMakesRequest{}
	mi := &file_proto_carapp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMakesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMakesRequest) ProtoMessage() {}

func (x *GetMakesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMakesRequest.ProtoReflect.Descriptor instead.
func (*GetMakesRequest) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{12}
}

type GetMakesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Makes         []*Make                `protobuf:"bytes,1,rep,name=makes,proto3" json:"makes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMakesResponse) Reset() {
	*x = GetMakesResponse{}
	mi := &file_proto_carapp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMakesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMakesResponse) ProtoMessage() {}

func (x *GetMakesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMakesResponse.ProtoReflect.Descriptor instead.
func (*GetMakesResponse) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{13}
}

func (x *GetMakesResponse) GetMakes() []*Make {
	if x != nil {
		return x.Makes
	}
	return nil
}

type GetModelsForMakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrandId       string                 `protobuf:"bytes,1,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelsForMakeRequest) Reset() {
	*x = GetModelsForMakeRequest{}
	mi := &file_proto_carapp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelsForMakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelsForMakeRequest) ProtoMessage() {}

func (x *GetModelsForMakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelsForMakeRequest.ProtoReflect.Descriptor instead.
func (*GetModelsForMakeRequest) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{14}
}

func (x *GetModelsForMakeRequest) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

type GetModelsForMakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelsForMakeResponse) Reset() {
	*x = GetModelsForMakeResponse{}
	mi := &file_proto_carapp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelsForMakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelsForMakeResponse) ProtoMessage() {}

func (x *GetModelsForMakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelsForMakeResponse.ProtoReflect.Descriptor instead.
func (*GetModelsForMakeResponse) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{15}
}

func (x *GetModelsForMakeResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

type BuyMobilRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MobilId       string                 `protobuf:"bytes,1,opt,name=mobil_id,json=mobilId,proto3" json:"mobil_id,omitempty"` // pembeli_id diambil dari JWT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyMobilRequest) Reset() {
	*x = BuyMobilRequest{}
	mi := &file_proto_carapp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyMobilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyMobilRequest) ProtoMessage() {}

func (x *BuyMobilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyMobilRequest.ProtoReflect.Descriptor instead.
func (*BuyMobilRequest) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{16}
}

func (x *BuyMobilRequest) GetMobilId() string {
	if x != nil {
		return x.MobilId
	}
	return ""
}

type TransaksiJualResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MobilId       string                 `protobuf:"bytes,2,opt,name=mobil_id,json=mobilId,proto3" json:"mobil_id,omitempty"`
	PenjualId     string                 `protobuf:"bytes,3,opt,name=penjual_id,json=penjualId,proto3" json:"penjual_id,omitempty"`
	PembeliId     string                 `protobuf:"bytes,4,opt,name=pembeli_id,json=pembeliId,proto3" json:"pembeli_id,omitempty"`
	Total         float64                `protobuf:"fixed64,5,opt,name=total,proto3" json:"total,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransaksiJualResponse) Reset() {
	*x = TransaksiJualResponse{}
	mi := &file_proto_carapp_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransaksiJualResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransaksiJualResponse) ProtoMessage() {}

func (x *TransaksiJualResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransaksiJualResponse.ProtoReflect.Descriptor instead.
func (*TransaksiJualResponse) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{17}
}

func (x *TransaksiJualResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransaksiJualResponse) GetMobilId() string {
	if x != nil {
		return x.MobilId
	}
	return ""
}

func (x *TransaksiJualResponse) GetPenjualId() string {
	if x != nil {
		return x.PenjualId
	}
	return ""
}

func (x *TransaksiJualResponse) GetPembeliId() string {
	if x != nil {
		return x.PembeliId
	}
	return ""
}

func (x *TransaksiJualResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TransaksiJualResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RentMobilRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MobilId        string                 `protobuf:"bytes,1,opt,name=mobil_id,json=mobilId,proto3" json:"mobil_id,omitempty"`
	TanggalMulai   string                 `protobuf:"bytes,2,opt,name=tanggal_mulai,json=tanggalMulai,proto3" json:"tanggal_mulai,omitempty"`       // Format: "YYYY-MM-DD"
	TanggalSelesai string                 `protobuf:"bytes,3,opt,name=tanggal_selesai,json=tanggalSelesai,proto3" json:"tanggal_selesai,omitempty"` // Format: "YYYY-MM-DD"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RentMobilRequest) Reset() {
	*x = RentMobilRequest{}
	mi := &file_proto_carapp_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RentMobilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentMobilRequest) ProtoMessage() {}

func (x *RentMobilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentMobilRequest.ProtoReflect.Descriptor instead.
func (*RentMobilRequest) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{18}
}

func (x *RentMobilRequest) GetMobilId() string {
	if x != nil {
		return x.MobilId
	}
	return ""
}

func (x *RentMobilRequest) GetTanggalMulai() string {
	if x != nil {
		return x.TanggalMulai
	}
	return ""
}

func (x *RentMobilRequest) GetTanggalSelesai() string {
	if x != nil {
		return x.TanggalSelesai
	}
	return ""
}

type CompleteRentalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RentalId      string                 `protobuf:"bytes,1,opt,name=rental_id,json=rentalId,proto3" json:"rental_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRentalRequest) Reset() {
	*x = CompleteRentalRequest{}
	mi := &file_proto_carapp_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRentalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRentalRequest) ProtoMessage() {}

func (x *CompleteRentalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRentalRequest.ProtoReflect.Descriptor instead.
func (*CompleteRentalRequest) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{19}
}

func (x *CompleteRentalRequest) GetRentalId() string {
	if x != nil {
		return x.RentalId
	}
	return ""
}

type TransaksiRentalResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MobilId        string                 `protobuf:"bytes,2,opt,name=mobil_id,json=mobilId,proto3" json:"mobil_id,omitempty"`
	PemilikId      string                 `protobuf:"bytes,3,opt,name=pemilik_id,json=pemilikId,proto3" json:"pemilik_id,omitempty"`
	PenyewaId      string                 `protobuf:"bytes,4,opt,name=penyewa_id,json=penyewaId,proto3" json:"penyewa_id,omitempty"`
	TanggalMulai   string                 `protobuf:"bytes,5,opt,name=tanggal_mulai,json=tanggalMulai,proto3" json:"tanggal_mulai,omitempty"`
	TanggalSelesai string                 `protobuf:"bytes,6,opt,name=tanggal_selesai,json=tanggalSelesai,proto3" json:"tanggal_selesai,omitempty"`
	Total          float64                `protobuf:"fixed64,7,opt,name=total,proto3" json:"total,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Denda          float64                `protobuf:"fixed64,9,opt,name=denda,proto3" json:"denda,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransaksiRentalResponse) Reset() {
	*x = TransaksiRentalResponse{}
	mi := &file_proto_carapp_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransaksiRentalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransaksiRentalResponse) ProtoMessage() {}

func (x *TransaksiRentalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransaksiRentalResponse.ProtoReflect.Descriptor instead.
func (*TransaksiRentalResponse) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{20}
}

func (x *TransaksiRentalResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransaksiRentalResponse) GetMobilId() string {
	if x != nil {
		return x.MobilId
	}
	return ""
}

func (x *TransaksiRentalResponse) GetPemilikId() string {
	if x != nil {
		return x.PemilikId
	}
	return ""
}

func (x *TransaksiRentalResponse) GetPenyewaId() string {
	if x != nil {
		return x.PenyewaId
	}
	return ""
}

func (x *TransaksiRentalResponse) GetTanggalMulai() string {
	if x != nil {
		return x.TanggalMulai
	}
	return ""
}

func (x *TransaksiRentalResponse) GetTanggalSelesai() string {
	if x != nil {
		return x.TanggalSelesai
	}
	return ""
}

func (x *TransaksiRentalResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TransaksiRentalResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransaksiRentalResponse) GetDenda() float64 {
	if x != nil {
		return x.Denda
	}
	return 0
}

type GetNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsRequest) Reset() {
	*x = GetNotificationsRequest{}
	mi := &file_proto_carapp_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsRequest) ProtoMessage() {}

func (x *GetNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{21}
}

type DashboardSummary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalMobilAnda     int32                  `protobuf:"varint,1,opt,name=total_mobil_anda,json=totalMobilAnda,proto3" json:"total_mobil_anda,omitempty"`
	TransaksiAktif     int32                  `protobuf:"varint,2,opt,name=transaksi_aktif,json=transaksiAktif,proto3" json:"transaksi_aktif,omitempty"`
	PendapatanTerakhir float64                `protobuf:"fixed64,3,opt,name=pendapatan_terakhir,json=pendapatanTerakhir,proto3" json:"pendapatan_terakhir,omitempty"`
	NotifikasiBaru     int32                  `protobuf:"varint,4,opt,name=notifikasi_baru,json=notifikasiBaru,proto3" json:"notifikasi_baru,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DashboardSummary) Reset() {
	*x = DashboardSummary{}
	mi := &file_proto_carapp_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardSummary) ProtoMessage() {}

func (x *DashboardSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carapp_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardSummary.ProtoReflect.Descriptor instead.
func (*DashboardSummary) Descriptor() ([]byte, []int) {
	return file_proto_carapp_proto_rawDescGZIP(), []int{22}
}

func (x *DashboardSummary) GetTotalMobilAnda() int32 {
	if x != nil {
		return x.TotalMobilAnda
	}
	return 0
}

func (x *DashboardSummary) GetTransaksiAktif() int32 {
	if x != nil {
		return x.TransaksiAktif
	}
	return 0
}

func (x *DashboardSummary) GetPendapatanTerakhir() float64 {
	if x != nil {
		return x.PendapatanTerakhir
	}
	return 0
}

func (x *DashboardSummary) GetNotifikasiBaru() int32 {
	if x != nil {
		return x.NotifikasiBaru
	}
	return 0
}

var File_proto_carapp_proto protoreflect.FileDescriptor

const file_proto_carapp_proto_rawDesc = "" +
	"\n" +
	"\x12proto/carapp.proto\x12\x06carapp\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa5\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa1\x03\n" +
	"\x05Mobil\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"owner_name\x18\r \x01(\tR\townerName\x12\x12\n" +
	"\x04merk\x18\x03 \x01(\tR\x04merk\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x14\n" +
	"\x05tahun\x18\x05 \x01(\x05R\x05tahun\x12\x18\n" +
	"\akondisi\x18\x06 \x01(\tR\akondisi\x12\x1c\n" +
	"\tdeskripsi\x18\a \x01(\tR\tdeskripsi\x12\x1d\n" +
	"\n" +
	"harga_jual\x18\b \x01(\x01R\thargaJual\x12\x19\n" +
	"\bfoto_url\x18\t \x01(\tR\afotoUrl\x12\x16\n" +
	"\x06lokasi\x18\n" +
	" \x01(\tR\x06lokasi\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x121\n" +
	"\x15harga_rental_per_hari\x18\x0e \x01(\x01R\x12hargaRentalPerHari\"\xeb\x01\n" +
	"\n" +
	"Notifikasi\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04tipe\x18\x03 \x01(\tR\x04tipe\x12\x14\n" +
	"\x05pesan\x18\x04 \x01(\tR\x05pesan\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x123\n" +
	"\aread_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06readAt\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"m\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"F\n" +
	"\fAuthResponse\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.carapp.UserR\x04user\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x91\x02\n" +
	"\x12CreateMobilRequest\x12\x12\n" +
	"\x04merk\x18\x01 \x01(\tR\x04merk\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x14\n" +
	"\x05tahun\x18\x03 \x01(\x05R\x05tahun\x12\x18\n" +
	"\akondisi\x18\x04 \x01(\tR\akondisi\x12\x1c\n" +
	"\tdeskripsi\x18\x05 \x01(\tR\tdeskripsi\x12\x1d\n" +
	"\n" +
	"harga_jual\x18\x06 \x01(\x01R\thargaJual\x12\x19\n" +
	"\bfoto_url\x18\a \x01(\tR\afotoUrl\x12\x16\n" +
	"\x06lokasi\x18\b \x01(\tR\x06lokasi\x121\n" +
	"\x15harga_rental_per_hari\x18\t \x01(\x01R\x12hargaRentalPerHari\"x\n" +
	"\x10ListMobilRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12(\n" +
	"\rfilter_status\x18\x03 \x01(\tH\x00R\ffilterStatus\x88\x01\x01B\x10\n" +
	"\x0e_filter_status\"P\n" +
	"\x11ListMobilResponse\x12%\n" +
	"\x06mobils\x18\x01 \x03(\v2\r.carapp.MobilR\x06mobils\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\",\n" +
	"\x0fGetMobilRequest\x12\x19\n" +
	"\bmobil_id\x18\x01 \x01(\tR\amobilId\"5\n" +
	"\x04Make\x12\x19\n" +
	"\bbrand_id\x18\x01 \x01(\tR\abrandId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"Q\n" +
	"\x05Model\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x19\n" +
	"\bbrand_id\x18\x02 \x01(\tR\abrandId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x11\n" +
	"\x0fGetMakesRequest\"6\n" +
	"\x10GetMakesResponse\x12\"\n" +
	"\x05makes\x18\x01 \x03(\v2\f.carapp.MakeR\x05makes\"4\n" +
	"\x17GetModelsForMakeRequest\x12\x19\n" +
	"\bbrand_id\x18\x01 \x01(\tR\abrandId\"A\n" +
	"\x18GetModelsForMakeResponse\x12%\n" +
	"\x06models\x18\x01 \x03(\v2\r.carapp.ModelR\x06models\",\n" +
	"\x0fBuyMobilRequest\x12\x19\n" +
	"\bmobil_id\x18\x01 \x01(\tR\amobilId\"\xae\x01\n" +
	"\x15TransaksiJualResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bmobil_id\x18\x02 \x01(\tR\amobilId\x12\x1d\n" +
	"\n" +
	"penjual_id\x18\x03 \x01(\tR\tpenjualId\x12\x1d\n" +
	"\n" +
	"pembeli_id\x18\x04 \x01(\tR\tpembeliId\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x01R\x05total\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"{\n" +
	"\x10RentMobilRequest\x12\x19\n" +
	"\bmobil_id\x18\x01 \x01(\tR\amobilId\x12#\n" +
	"\rtanggal_mulai\x18\x02 \x01(\tR\ftanggalMulai\x12'\n" +
	"\x0ftanggal_selesai\x18\x03 \x01(\tR\x0etanggalSelesai\"4\n" +
	"\x15CompleteRentalRequest\x12\x1b\n" +
	"\trental_id\x18\x01 \x01(\tR\brentalId\"\x94\x02\n" +
	"\x17TransaksiRentalResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bmobil_id\x18\x02 \x01(\tR\amobilId\x12\x1d\n" +
	"\n" +
	"pemilik_id\x18\x03 \x01(\tR\tpemilikId\x12\x1d\n" +
	"\n" +
	"penyewa_id\x18\x04 \x01(\tR\tpenyewaId\x12#\n" +
	"\rtanggal_mulai\x18\x05 \x01(\tR\ftanggalMulai\x12'\n" +
	"\x0ftanggal_selesai\x18\x06 \x01(\tR\x0etanggalSelesai\x12\x14\n" +
	"\x05total\x18\a \x01(\x01R\x05total\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x14\n" +
	"\x05denda\x18\t \x01(\x01R\x05denda\"\x19\n" +
	"\x17GetNotificationsRequest\"\xbf\x01\n" +
	"\x10DashboardSummary\x12(\n" +
	"\x10total_mobil_anda\x18\x01 \x01(\x05R\x0etotalMobilAnda\x12'\n" +
	"\x0ftransaksi_aktif\x18\x02 \x01(\x05R\x0etransaksiAktif\x12/\n" +
	"\x13pendapatan_terakhir\x18\x03 \x01(\x01R\x12pendapatanTerakhir\x12'\n" +
	"\x0fnotifikasi_baru\x18\x04 \x01(\x05R\x0enotifikasiBaru2}\n" +
	"\vAuthService\x129\n" +
	"\bRegister\x12\x17.carapp.RegisterRequest\x1a\x14.carapp.AuthResponse\x123\n" +
	"\x05Login\x12\x14.carapp.LoginRequest\x1a\x14.carapp.AuthResponse2\xbe\x01\n" +
	"\fMobilService\x128\n" +
	"\vCreateMobil\x12\x1a.carapp.CreateMobilRequest\x1a\r.carapp.Mobil\x12@\n" +
	"\tListMobil\x12\x18.carapp.ListMobilRequest\x1a\x19.carapp.ListMobilResponse\x122\n" +
	"\bGetMobil\x12\x17.carapp.GetMobilRequest\x1a\r.carapp.Mobil2\xa8\x01\n" +
	"\x10NhtsaDataService\x12=\n" +
	"\bGetMakes\x12\x17.carapp.GetMakesRequest\x1a\x18.carapp.GetMakesResponse\x12U\n" +
	"\x10GetModelsForMake\x12\x1f.carapp.GetModelsForMakeRequest\x1a .carapp.GetModelsForMakeResponse2\xf0\x01\n" +
	"\x10TransaksiService\x12B\n" +
	"\bBuyMobil\x12\x17.carapp.BuyMobilRequest\x1a\x1d.carapp.TransaksiJualResponse\x12F\n" +
	"\tRentMobil\x12\x18.carapp.RentMobilRequest\x1a\x1f.carapp.TransaksiRentalResponse\x12P\n" +
	"\x0eCompleteRental\x12\x1d.carapp.CompleteRentalRequest\x1a\x1f.carapp.TransaksiRentalResponse2^\n" +
	"\x11NotifikasiService\x12I\n" +
	"\x10GetNotifications\x12\x1f.carapp.GetNotificationsRequest\x1a\x12.carapp.Notifikasi0\x012T\n" +
	"\x10DashboardService\x12@\n" +
	"\fGetDashboard\x12\x16.google.protobuf.Empty\x1a\x18.carapp.DashboardSummaryB\x14Z\x12carapp.com/m/protob\x06proto3"

var (
	file_proto_carapp_proto_rawDescOnce sync.Once
	file_proto_carapp_proto_rawDescData []byte
)

func file_proto_carapp_proto_rawDescGZIP() []byte {
	file_proto_carapp_proto_rawDescOnce.Do(func() {
		file_proto_carapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_carapp_proto_rawDesc), len(file_proto_carapp_proto_rawDesc)))
	})
	return file_proto_carapp_proto_rawDescData
}

var file_proto_carapp_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_carapp_proto_goTypes = []any{
	(*User)(nil),                     // 0: carapp.User
	(*Mobil)(nil),                    // 1: carapp.Mobil
	(*Notifikasi)(nil),               // 2: carapp.Notifikasi
	(*RegisterRequest)(nil),          // 3: carapp.RegisterRequest
	(*LoginRequest)(nil),             // 4: carapp.LoginRequest
	(*AuthResponse)(nil),             // 5: carapp.AuthResponse
	(*CreateMobilRequest)(nil),       // 6: carapp.CreateMobilRequest
	(*ListMobilRequest)(nil),         // 7: carapp.ListMobilRequest
	(*ListMobilResponse)(nil),        // 8: carapp.ListMobilResponse
	(*GetMobilRequest)(nil),          // 9: carapp.GetMobilRequest
	(*Make)(nil),                     // 10: carapp.Make
	(*Model)(nil),                    // 11: carapp.Model
	(*GetMakesRequest)(nil),          // 12: carapp.GetMakesRequest
	(*GetMakesResponse)(nil),         // 13: carapp.GetMakesResponse
	(*GetModelsForMakeRequest)(nil),  // 14: carapp.GetModelsForMakeRequest
	(*GetModelsForMakeResponse)(nil), // 15: carapp.GetModelsForMakeResponse
	(*BuyMobilRequest)(nil),          // 16: carapp.BuyMobilRequest
	(*TransaksiJualResponse)(nil),    // 17: carapp.TransaksiJualResponse
	(*RentMobilRequest)(nil),         // 18: carapp.RentMobilRequest
	(*CompleteRentalRequest)(nil),    // 19: carapp.CompleteRentalRequest
	(*TransaksiRentalResponse)(nil),  // 20: carapp.TransaksiRentalResponse
	(*GetNotificationsRequest)(nil),  // 21: carapp.GetNotificationsRequest
	(*DashboardSummary)(nil),         // 22: carapp.DashboardSummary
	(*timestamppb.Timestamp)(nil),    // 23: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 24: google.protobuf.Empty
}
var file_proto_carapp_proto_depIdxs = []int32{
	23, // 0: carapp.User.created_at:type_name -> google.protobuf.Timestamp
	23, // 1: carapp.Mobil.created_at:type_name -> google.protobuf.Timestamp
	23, // 2: carapp.Notifikasi.read_at:type_name -> google.protobuf.Timestamp
	23, // 3: carapp.Notifikasi.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: carapp.AuthResponse.user:type_name -> carapp.User
	1,  // 5: carapp.ListMobilResponse.mobils:type_name -> carapp.Mobil
	10, // 6: carapp.GetMakesResponse.makes:type_name -> carapp.Make
	11, // 7: carapp.GetModelsForMakeResponse.models:type_name -> carapp.Model
	3,  // 8: carapp.AuthService.Register:input_type -> carapp.RegisterRequest
	4,  // 9: carapp.AuthService.Login:input_type -> carapp.LoginRequest
	6,  // 10: carapp.MobilService.CreateMobil:input_type -> carapp.CreateMobilRequest
	7,  // 11: carapp.MobilService.ListMobil:input_type -> carapp.ListMobilRequest
	9,  // 12: carapp.MobilService.GetMobil:input_type -> carapp.GetMobilRequest
	12, // 13: carapp.NhtsaDataService.GetMakes:input_type -> carapp.GetMakesRequest
	14, // 14: carapp.NhtsaDataService.GetModelsForMake:input_type -> carapp.GetModelsForMakeRequest
	16, // 15: carapp.TransaksiService.BuyMobil:input_type -> carapp.BuyMobilRequest
	18, // 16: carapp.TransaksiService.RentMobil:input_type -> carapp.RentMobilRequest
	19, // 17: carapp.TransaksiService.CompleteRental:input_type -> carapp.CompleteRentalRequest
	21, // 18: carapp.NotifikasiService.GetNotifications:input_type -> carapp.GetNotificationsRequest
	24, // 19: carapp.DashboardService.GetDashboard:input_type -> google.protobuf.Empty
	5,  // 20: carapp.AuthService.Register:output_type -> carapp.AuthResponse
	5,  // 21: carapp.AuthService.Login:output_type -> carapp.AuthResponse
	1,  // 22: carapp.MobilService.CreateMobil:output_type -> carapp.Mobil
	8,  // 23: carapp.MobilService.ListMobil:output_type -> carapp.ListMobilResponse
	1,  // 24: carapp.MobilService.GetMobil:output_type -> carapp.Mobil
	13, // 25: carapp.NhtsaDataService.GetMakes:output_type -> carapp.GetMakesResponse
	15, // 26: carapp.NhtsaDataService.GetModelsForMake:output_type -> carapp.GetModelsForMakeResponse
	17, // 27: carapp.TransaksiService.BuyMobil:output_type -> carapp.TransaksiJualResponse
	20, // 28: carapp.TransaksiService.RentMobil:output_type -> carapp.TransaksiRentalResponse
	20, // 29: carapp.TransaksiService.CompleteRental:output_type -> carapp.TransaksiRentalResponse
	2,  // 30: carapp.NotifikasiService.GetNotifications:output_type -> carapp.Notifikasi
	22, // 31: carapp.DashboardService.GetDashboard:output_type -> carapp.DashboardSummary
	20, // [20:32] is the sub-list for method output_type
	8,  // [8:20] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_carapp_proto_init() }
func file_proto_carapp_proto_init() {
	if File_proto_carapp_proto != nil {
		return
	}
	file_proto_carapp_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_carapp_proto_rawDesc), len(file_proto_carapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_proto_carapp_proto_goTypes,
		DependencyIndexes: file_proto_carapp_proto_depIdxs,
		MessageInfos:      file_proto_carapp_proto_msgTypes,
	}.Build()
	File_proto_carapp_proto = out.File
	file_proto_carapp_proto_goTypes = nil
	file_proto_carapp_proto_depIdxs = nil
}
